// src/components/ForecastCard.vue
<script setup lang="ts">
import type { WeatherForecast } from '@/App.vue'

const props = defineProps<{
  forecast: WeatherForecast
  showRemoveButton?: boolean
}>()

const emit = defineEmits<{
  (e: 'remove', id: string): void
}>()

</script>

<template>
  <div class="card forecast-tile">
    <div class="card-image has-text-centered pt-4">
      <img :src="forecast.weatherImage" :alt="forecast.weatherCondition" class="weather-icon" />
    </div>
    <div class="card-content">
      <div class="has-text-centered mb-3">
        <p class="title is-5 mb-1">{{ forecast.city }}</p>
        <p class="subtitle is-6 mb-2">{{ forecast.country }}</p>
        <p class="is-size-7 has-text-grey">{{ forecast.weatherCondition }}</p>
      </div>
      
      <div class="has-text-centered py-4 temp-section">
        <p class="is-size-2 has-text-weight-bold">{{ forecast.temperature }}°C</p>
      </div>

      <div class="content is-small">
        <div class="level is-mobile mb-2">
          <div class="level-left has-text-grey">💧 Humidity:</div>
          <div class="level-right has-text-weight-semibold">{{ forecast.humidity }}%</div>
        </div>
        <div class="level is-mobile mb-2">
          <div class="level-left has-text-grey">💨 Wind:</div>
          <div class="level-right has-text-weight-semibold">{{ forecast.windSpeed }} km/h</div>
        </div>
        <div class="level is-mobile mb-2">
          <div class="level-left has-text-grey">🎚️ Pressure:</div>
          <div class="level-right has-text-weight-semibold">{{ forecast.pressure }} hPa</div>
        </div>
        <div class="level is-mobile mb-2">
          <div class="level-left has-text-grey">🌅 Sunrise:</div>
          <div class="level-right has-text-weight-semibold">{{ forecast.sunrise }}</div>
        </div>
        <div class="level is-mobile mb-2">
          <div class="level-left has-text-grey">🌇 Sunset:</div>
          <div class="level-right has-text-weight-semibold">{{ forecast.sunset }}</div>
        </div>
      </div>
    </div>
    <footer class="card-footer" v-if="showRemoveButton">
      <a class="card-footer-item has-text-danger" @click.prevent="emit('remove', forecast.id)">
        Remove
      </a>
    </footer>
  </div>
</template>

<style scoped>
.forecast-tile {
  height: 100%;
  transition: transform 0.2s;
}

.forecast-tile:hover {
  transform: translateY(-4px);
}

.weather-icon {
  width: 80px;
  height: 80px;
}

.temp-section {
  border-top: 1px solid #e8e8e8;
  border-bottom: 1px solid #e8e8e8;
}
</style>

// app/components/ForecastCard.tsx
import type { WeatherForecast } from '~/root.tsx'

interface ForecastCardProps {
  forecast: WeatherForecast;
  showRemoveButton?: boolean;
}

export default function ForecastCard({ forecast, showRemoveButton }: ForecastCardProps) {
  return (
    <div className="card forecast-tile">
      <div className="card-image has-text-centered pt-4">
        {/* <img src={forecast.weatherImage} alt={forecast.weatherCondition} className="weather-icon" /> */}
      </div>
      <div className="card-content">
        <div className="has-text-centered mb-3">
          <p className="title is-5 mb-1">{ forecast.city }</p>
          <p className="subtitle is-6 mb-2">{ forecast.country }</p>
          <p className="is-size-7 has-text-grey">{ forecast.weatherCondition }</p>
        </div>
        
        <div className="has-text-centered py-4 temp-section">
          <p className="is-size-2 has-text-weight-bold">{ forecast.temperature }°C</p>
        </div>

        <div className="content is-small">
          <div className="level is-mobile mb-2">
            <div className="level-left has-text-grey">💧 Humidity:</div>
            <div className="level-right has-text-weight-semibold">{ forecast.humidity }%</div>
          </div>
          <div className="level is-mobile mb-2">
            <div className="level-left has-text-grey">💨 Wind:</div>
            <div className="level-right has-text-weight-semibold">{ forecast.windSpeed } km/h</div>
          </div>
          <div className="level is-mobile mb-2">
            <div className="level-left has-text-grey">🎚️ Pressure:</div>
            <div className="level-right has-text-weight-semibold">{ forecast.pressure } hPa</div>
          </div>
          <div className="level is-mobile mb-2">
            <div className="level-left has-text-grey">🌅 Sunrise:</div>
            <div className="level-right has-text-weight-semibold">{ forecast.sunrise }</div>
          </div>
          <div className="level is-mobile mb-2">
            <div className="level-left has-text-grey">🌇 Sunset:</div>
            <div className="level-right has-text-weight-semibold">{ forecast.sunset }</div>
          </div>
        </div>
      </div>
      {showRemoveButton && (
      <footer className="card-footer">
        <a className="card-footer-item has-text-danger">
          Remove
        </a>
      </footer>
      )}
    </div>
  )
}
