// app/components/AddForecastModal.tsx
import { useState } from "react";
import type { WeatherForecast } from "~/root";
import ForecastCard from "~/components/ForecastCard";
import { fetchWeather, parseWeatherData } from "~/services/weatherApi";

interface AddForecastModalProps {
  isVisible: boolean;
  onClose: () => void;
  onAdd: (forecast: string) => void;
  onError: (message: string) => void;
}

export default function AddForecastModal({
  isVisible,
  onClose,
  onAdd,
  onError,
}: AddForecastModalProps) {
  const [forecasts, setForecasts] = useState<WeatherForecast[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedForecast, setSelectedForecast] = useState<WeatherForecast | null>(null);

  function handleSearch(event: React.ChangeEvent<HTMLInputElement>) {
    const value = event.target.value;
    setSearchQuery(value);

    fetchWeather(value)
      .then((data) => {
        const parsedForecast = parseWeatherData(data.data);
        setForecasts([parsedForecast]);
        setSelectedForecast(parsedForecast);
      })
      .catch((error) => {
        console.error(`Error fetching weather data for ${value}:`, error);
        const errorMessage =
          error.response?.data?.message || error.message || "Unknown error";
        const errorCode =
          error.response?.data?.cod || error.response?.status || "N/A";
        onError(`Error (${errorCode}) for ${value}: ${errorMessage}`);
      });
  }

  function handleAdd() {
    if (selectedForecast) {
      const queryToAdd = searchQuery;
      setForecasts([]);
      setSearchQuery("");
      onAdd(queryToAdd);
      onClose();
    }
  }

  if (!isVisible) return null;

  return (
    <div className="modal is-active">
      <div className="modal-background" onClick={onClose}></div>
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">Add Weather Forecast</p>
          <button className="delete" aria-label="close" onClick={onClose}></button>
        </header>

        <section className="modal-card-body">
          <div className="field mb-5">
            <label className="label">Location</label>
            <div className="control">
              <input
                className="input is-medium"
                type="text"
                placeholder="City, coordinates (lat,lon), or zip code"
                value={searchQuery}
                onChange={handleSearch}
              />
            </div>
            <p className="help">Press Enter or click away to search</p>
          </div>

          {forecasts && forecasts.length > 0 ? (
            <div className="preview-section">
              <p className="subtitle is-6 mb-3">Preview:</p>
              {forecasts.map((forecast) => (
                <ForecastCard key={forecast.id} forecast={forecast} />
              ))}
            </div>
          ) : searchQuery ? (
            <div className="has-text-centered py-5">
              <p className="has-text-grey">Searching...</p>
            </div>
          ) : null}
        </section>

        <footer className="modal-card-foot" style={{ justifyContent: "space-between" }}>
          <button className="button" onClick={onClose}>
            Cancel
          </button>
          <button
            className="button is-primary"
            disabled={!selectedForecast}
            onClick={handleAdd}
          >
            Add Forecast
          </button>
        </footer>
      </div>
    </div>
  );
}

// src/components/AddForecastModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { WeatherForecast } from '@/App.vue'
import ForecastCard from '@/components/ForecastCard.vue'
import { fetchWeather, parseWeatherData } from '@/services/weatherApi'

const props = defineProps<{
    isVisible: boolean
}>()

const emit = defineEmits<{
    (e: 'close'): void
    (e: 'add', forecast: string): void
    (e: 'error', message: string): void
}>()

const forecasts = ref<WeatherForecast[]>()
const searchQuery = ref('')
const selectedForecast = ref<WeatherForecast | null>(null)

function handleSearch(event: Event) {
  const target = event.target as HTMLInputElement
  searchQuery.value = target.value

  fetchWeather(searchQuery.value).then(data => {
    const parsedForecast = parseWeatherData(data.data)
    forecasts.value = [parsedForecast]
    selectedForecast.value = parsedForecast
  }).catch(error => {
    console.error(`Error fetching weather data for ${searchQuery.value}:`, error)
    
    const errorMessage = error.response?.data?.message || error.message || 'Unknown error'
    const errorCode = error.response?.data?.cod || error.response?.status || 'N/A'
    
    emit('error', `Error (${errorCode}) for ${searchQuery.value}: ${errorMessage}`)
  })
}

function handleAdd() {
  if (selectedForecast.value) {
    const queryToAdd = searchQuery.value
    forecasts.value = []
    searchQuery.value = ''
    emit('add', queryToAdd)
    emit('close')
  }
}

</script>

<template>
    <div v-if="isVisible" class="modal is-active">
      <div class="modal-background" @click="emit('close')"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Add Weather Forecast</p>
          <button class="delete" aria-label="close" @click="emit('close')"></button>
        </header>
        
        <section class="modal-card-body">
          <div class="field">
            <div class="control">
              <input 
                class="input" 
                type="text" 
                placeholder="Enter city OR coordinates lat,lon OR zip,country)" 
                @change="handleSearch" 
              />
            </div>
          </div>

          <div v-if="searchQuery">
            <p class="mb-3">Searching for: <strong>{{ searchQuery }}</strong></p>
            <div v-for="forecast in forecasts" :key="forecast.id">
              <ForecastCard :forecast="forecast" />
            </div>
          </div>
        </section>
        
        <footer class="modal-card-foot">
          <div class="buttons">
            <button 
              class="button is-success" 
              :disabled="!selectedForecast"
              @click="handleAdd"
            >
              Add Forecast
            </button>
            <button class="button" @click="emit('close')">Cancel</button>
          </div>
        </footer>
      </div>
    </div>
</template>
